import logging
from backend.recovery.schemas import PaymentContext
from backend.policy.schemas import PolicyConfig, ExecutionState, PolicyDecision

# List of supported actions generated by candidate logic
SUPPORTED_ACTIONS = {"retry_now", "retry_later", "payment_link", "escalate", "stop"}
RETRY_ACTIONS = {"retry_now", "retry_later"}
CUSTOMER_FACING_ACTIONS = {"payment_link"}
NON_RETRYABLE_FAILURES = {"permanent_decline"}

logger = logging.getLogger(__name__)

def evaluate_policy(
    context: PaymentContext,
    proposed_action: str,
    execution_state: ExecutionState,
    config: PolicyConfig = PolicyConfig()
) -> PolicyDecision:
    try:
        violations = []
        
        # Rule G: Unknown/invalid action
        if proposed_action not in SUPPORTED_ACTIONS:
            violations.append("Unsupported recovery action")
            
        # Rule F: Duplicate execution / idempotency
        if execution_state.event_id in execution_state.previously_executed_events:
            violations.append("Duplicate recovery event/action")
            
        # Rule C: Successful payment cannot be retried
        if proposed_action in RETRY_ACTIONS and execution_state.is_already_successful:
            violations.append("Payment already successful")
            
        # Rule B: Permanent failure cannot be retried
        if proposed_action in RETRY_ACTIONS and context.failure_type in NON_RETRYABLE_FAILURES:
            violations.append("Failure type is non-retryable")
            
        # Rule A: Maximum retries
        if proposed_action in RETRY_ACTIONS and context.retry_count >= config.max_retries:
            violations.append("Maximum retry limit reached")
            
        # Rule D: Autonomous amount limit
        if proposed_action in RETRY_ACTIONS and context.amount > config.max_autonomous_amount:
            violations.append("Amount exceeds autonomous execution limit")
            
        # Rule E: Maximum customer contacts
        if proposed_action in CUSTOMER_FACING_ACTIONS and execution_state.customer_contacts_count >= config.max_customer_contacts:
            violations.append("Maximum customer contacts reached")
            
        allowed = len(violations) == 0
        requires_escalation = False
        
        if not allowed:
            # If the original proposed action is escalate or stop, it might just be the duplicate rule that caught it.
            # Usually, a block means we need escalation unless it's a stop.
            requires_escalation = True
            reason = violations[0] if violations else "Blocked by policy"
        else:
            reason = "Authorized"
            
        return PolicyDecision(
            allowed=allowed,
            action=proposed_action,
            reason=reason,
            violations=violations,
            requires_escalation=requires_escalation,
            policy_version=config.policy_version
        )
        
    except Exception as e:
        logger.error(f"Policy engine error: {e}")
        # Rule H: Policy engine failure must fail closed
        return PolicyDecision(
            allowed=False,
            action=proposed_action,
            reason="Internal policy evaluation error",
            violations=["Internal error"],
            requires_escalation=True,
            policy_version=config.policy_version if 'config' in locals() else "unknown"
        )
